repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [ "--fix" ]  # Lint and auto-fix issues
    - id: ruff-format  # Ensure formatting is correct
    - id: ruff
      name: "Ruff Import Sort"
      args: [ "check", "--select", "I", "--fix" ]