# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment_module/protos/account.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "payment_module/protos/account.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#payment_module/protos/account.proto\x12\x07\x61\x63\x63ount\x1a\x1bgoogle/protobuf/empty.proto"3\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t"\x11\n\x0fUserListRequest"!\n\x13UserRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x88\x02\n\x0eUserController\x12\x33\n\x04List\x12\x18.account.UserListRequest\x1a\r.account.User"\x00\x30\x01\x12(\n\x06\x43reate\x12\r.account.User\x1a\r.account.User"\x00\x12\x39\n\x08Retrieve\x12\x1c.account.UserRetrieveRequest\x1a\r.account.User"\x00\x12(\n\x06Update\x12\r.account.User\x1a\r.account.User"\x00\x12\x32\n\x07\x44\x65stroy\x12\r.account.User\x1a\x16.google.protobuf.Empty"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "payment_module.protos.account_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_USER"]._serialized_start = 77
    _globals["_USER"]._serialized_end = 128
    _globals["_USERLISTREQUEST"]._serialized_start = 130
    _globals["_USERLISTREQUEST"]._serialized_end = 147
    _globals["_USERRETRIEVEREQUEST"]._serialized_start = 149
    _globals["_USERRETRIEVEREQUEST"]._serialized_end = 182
    _globals["_USERCONTROLLER"]._serialized_start = 185
    _globals["_USERCONTROLLER"]._serialized_end = 449
# @@protoc_insertion_point(module_scope)
