# Generated by Django 5.1.4 on 2025-01-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('fund_type', models.CharField(choices=[('Equity', 'Equity'), ('Debt', 'Debt'), ('Hybrid', 'Hybrid')], max_length=10)),
                ('nav', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
    ]
